/**
 * WhatStack API
 * Visit our [API documentation](https://docs.whatstack.io/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WhatStackApi);
  }
}(this, function(expect, WhatStackApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WhatStackApi.TechnologyResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TechnologyResult', function() {
    it('should create an instance of TechnologyResult', function() {
      // uncomment below and update the code to test TechnologyResult
      //var instance = new WhatStackApi.TechnologyResult();
      //expect(instance).to.be.a(WhatStackApi.TechnologyResult);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new WhatStackApi.TechnologyResult();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new WhatStackApi.TechnologyResult();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new WhatStackApi.TechnologyResult();
      //expect(instance).to.be();
    });

    it('should have the property logo (base name: "logo")', function() {
      // uncomment below and update the code to test the property logo
      //var instance = new WhatStackApi.TechnologyResult();
      //expect(instance).to.be();
    });

    it('should have the property origin (base name: "origin")', function() {
      // uncomment below and update the code to test the property origin
      //var instance = new WhatStackApi.TechnologyResult();
      //expect(instance).to.be();
    });

  });

}));
