/**
 * WhatStack API
 * Visit our [API documentation](https://docs.whatstack.io/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DomainsSearchResult from '../model/DomainsSearchResult';

/**
* Domains service.
* @module api/DomainsApi
* @version 1.0.0
*/
export default class DomainsApi {

    /**
    * Constructs a new DomainsApi. 
    * @alias module:api/DomainsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the domainsSearch operation.
     * @callback module:api/DomainsApi~domainsSearchCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DomainsSearchResult>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Perform a technology lookup against one or multiple domains
     * Perform a technology lookup against one or multiple domains. TIER 3
     * @param {Array.<String>} requestBody An array of domains
     * @param {module:api/DomainsApi~domainsSearchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DomainsSearchResult>}
     */
    domainsSearch(requestBody, callback) {
      let postBody = requestBody;
      // verify the required parameter 'requestBody' is set
      if (requestBody === undefined || requestBody === null) {
        throw new Error("Missing the required parameter 'requestBody' when calling domainsSearch");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [DomainsSearchResult];
      return this.apiClient.callApi(
        '/domains/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
