/**
 * WhatStack API
 * Visit our [API documentation](https://docs.whatstack.io/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Technology from '../model/Technology';

/**
* Technologies service.
* @module api/TechnologiesApi
* @version 1.0.0
*/
export default class TechnologiesApi {

    /**
    * Constructs a new TechnologiesApi. 
    * @alias module:api/TechnologiesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getTechnologies operation.
     * @callback module:api/TechnologiesApi~getTechnologiesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Technology>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retreive the list of technologies
     * Retreive the list of technologies. TIER 3
     * @param {module:api/TechnologiesApi~getTechnologiesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Technology>}
     */
    getTechnologies(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Technology];
      return this.apiClient.callApi(
        '/technologies', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
