/**
 * WhatStack API
 * Visit our [API documentation](https://docs.whatstack.io/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TechnologyResult from './TechnologyResult';

/**
 * The DomainsSearchResult model module.
 * @module model/DomainsSearchResult
 * @version 1.0.0
 */
class DomainsSearchResult {
    /**
     * Constructs a new <code>DomainsSearchResult</code>.
     * DomainsSearchResult.
     * @alias module:model/DomainsSearchResult
     */
    constructor() { 
        
        DomainsSearchResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DomainsSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DomainsSearchResult} obj Optional instance to populate.
     * @return {module:model/DomainsSearchResult} The populated <code>DomainsSearchResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DomainsSearchResult();

            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('stack')) {
                obj['stack'] = ApiClient.convertToType(data['stack'], [TechnologyResult]);
            }
            if (data.hasOwnProperty('profile')) {
                obj['profile'] = ApiClient.convertToType(data['profile'], Object);
            }
        }
        return obj;
    }


}

/**
 * Domain
 * @member {String} domain
 */
DomainsSearchResult.prototype['domain'] = undefined;

/**
 * Stack
 * @member {Array.<module:model/TechnologyResult>} stack
 */
DomainsSearchResult.prototype['stack'] = undefined;

/**
 * Organization profile
 * @member {Object} profile
 */
DomainsSearchResult.prototype['profile'] = undefined;






export default DomainsSearchResult;

