/**
 * WhatStack API
 * Visit our [API documentation](https://docs.whatstack.io/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Technology model module.
 * @module model/Technology
 * @version 1.0.0
 */
class Technology {
    /**
     * Constructs a new <code>Technology</code>.
     * Technology.
     * @alias module:model/Technology
     */
    constructor() { 
        
        Technology.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Technology</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Technology} obj Optional instance to populate.
     * @return {module:model/Technology} The populated <code>Technology</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Technology();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Technology code
 * @member {String} code
 */
Technology.prototype['code'] = undefined;

/**
 * Technology name
 * @member {String} name
 */
Technology.prototype['name'] = undefined;

/**
 * Technology category
 * @member {String} category
 */
Technology.prototype['category'] = undefined;

/**
 * Technology logo
 * @member {String} logo
 */
Technology.prototype['logo'] = undefined;






export default Technology;

