/**
 * WhatStack API
 * Visit our [API documentation](https://docs.whatstack.io/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TechnologyResult model module.
 * @module model/TechnologyResult
 * @version 1.0.0
 */
class TechnologyResult {
    /**
     * Constructs a new <code>TechnologyResult</code>.
     * TechnologyResult.
     * @alias module:model/TechnologyResult
     */
    constructor() { 
        
        TechnologyResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TechnologyResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TechnologyResult} obj Optional instance to populate.
     * @return {module:model/TechnologyResult} The populated <code>TechnologyResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TechnologyResult();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
            if (data.hasOwnProperty('origin')) {
                obj['origin'] = ApiClient.convertToType(data['origin'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Technology code
 * @member {String} code
 */
TechnologyResult.prototype['code'] = undefined;

/**
 * Technology name
 * @member {String} name
 */
TechnologyResult.prototype['name'] = undefined;

/**
 * Technology category
 * @member {String} category
 */
TechnologyResult.prototype['category'] = undefined;

/**
 * Technology logo
 * @member {String} logo
 */
TechnologyResult.prototype['logo'] = undefined;

/**
 * Detection origin
 * @member {String} origin
 */
TechnologyResult.prototype['origin'] = undefined;






export default TechnologyResult;

